apiVersion: v1
kind: Service
metadata:
  name: iperf-server
  labels:
    app: iperf-server
spec:
  type: NodePort
  ports:
  - port: 5201
    targetPort: iperf-server
    protocol: TCP
    name: iperf-server
  selector:
    app: iperf-server
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-server
  labels: 
    app: iperf-server
spec:
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      containers:
      - name: iperf3
        image: quay.io/networkstatic/iperf3
        args: ["-s"]
        ports:
        - containerPort: 5201
          name: iperf-server
      terminationGracePeriodSeconds: 60
